### ISSUE TITLE
Flapjack crashing when jabber server is restarted

### ISSUE THREAD

**Issue by jessereynolds** [flapjack/flapjack#115]
When the jabber server is restarted (OpenFire in this case) Flapjack crashes. 

There were a couple of crashes during the restart, here's some pertinent log entries.

```
2013-01-03T09:43:48+1100 [WARN] :: flapjack-jabber :: disconnect handler called
2013-01-03T09:43:48+1100 [WARN] :: flapjack-jabber :: jabbers disconnected! reconnecting after a short deley ...
2013-01-03T09:43:49+1100 [INFO] :: flapjack-jabber :: Jabber Connected
2013-01-03T09:43:49+1100 [INFO] :: flapjack-jabber :: Joining room log@conference.jabber.xyz.dom
2013-01-03T09:43:49+1100 [INFO] :: flapjack-jabber :: Joining room flapjack-oobetet@conference.jabber.xyz.dom
...
2013-01-03T09:43:49+1100 [INFO] :: flapjack-jabber :: sending to group chat: ERROR - couldn't ACK 166343382 - not found
2013-01-03T09:43:49+1100 [INFO] :: flapjack-jabber :: sending to group chat: so you want me to test notifications for entity: foo.xyz.dom, check: test eh? ... well OK!
Stream Error (system-shutdown): 
/opt/rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/blather-0.8.0/lib/blather/client/client.rb:232:in `block in setup_initial_handlers'
/opt/rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/blather-0.8.0/lib/blather/client/client.rb:295:in `call'
/opt/rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/blather-0.8.0/lib/blather/client/client.rb:295:in `call_handler'
/opt/rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/blather-0.8.0/lib/blather/client/client.rb:286:in `block (2 levels) in call_handler_for'
/opt/rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/blather-0.8.0/lib/blather/client/client.rb:286:in `catch'
/opt/rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/blather-0.8.0/lib/blather/client/client.rb:286:in `block in call_handler_for'
/opt/rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/blather-0.8.0/lib/blather/client/client.rb:285:in `each'
/opt/rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/blather-0.8.0/lib/blather/client/client.rb:285:in `find'
/opt/rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/blather-0.8.0/lib/blather/client/client.rb:285:in `call_handler_for'
/opt/rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/blather-0.8.0/lib/blather/client/client.rb:278:in `block in handle_stanza'
/opt/rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/blather-0.8.0/lib/blather/client/client.rb:277:in `each'
/opt/rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/blather-0.8.0/lib/blather/client/client.rb:277:in `handle_stanza'
/opt/rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/blather-0.8.0/lib/blather/client/client.rb:194:in `block in handle_data'
/opt/rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/blather-0.8.0/lib/blather/client/client.rb:192:in `catch'
/opt/rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/blather-0.8.0/lib/blather/client/client.rb:192:in `handle_data'
/opt/rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/blather-0.8.0/lib/blather/client/client.rb:63:in `block in initialize'
/opt/rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/girl_friday-0.10.0/lib/girl_friday/work_queue.rb:147:in `call'
/opt/rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/girl_friday-0.10.0/lib/girl_friday/work_queue.rb:147:in `block (2 levels) in start'
/opt/rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/girl_friday-0.10.0/lib/girl_friday/actor.rb:86:in `call'
/opt/rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/girl_friday-0.10.0/lib/girl_friday/actor.rb:86:in `block in spawn_link'
/opt/rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/girl_friday-0.10.0/lib/girl_friday/actor.rb:69:in `call'
/opt/rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/girl_friday-0.10.0/lib/girl_friday/actor.rb:69:in `block (2 levels) in spawn'
/opt/rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/girl_friday-0.10.0/lib/girl_friday/actor.rb:212:in `block in initialize'
/opt/rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/girl_friday-0.10.0/lib/girl_friday/actor.rb:377:in `watchdog'
/opt/rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/girl_friday-0.10.0/lib/girl_friday/actor.rb:212:in `initialize'
/opt/rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/girl_friday-0.10.0/lib/girl_friday/actor.rb:66:in `new'
/opt/rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/girl_friday-0.10.0/lib/girl_friday/actor.rb:66:in `block in spawn'
2013-01-03T09:43:49+1100 [INFO] :: flapjack-jabber :: sending to group chat: Flapjack 0.6.60 process 31233 on flapjack.xyz.dom 
Boot time: 2012-12-30 18:54:23 +1100
User CPU Time: 34325.79
System CPU Time: 13927.82
Linux flapjack 3.2.0-23-generic #36-Ubuntu SMP Tue Apr 10 20:39:51 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux

2013-01-03T09:43:49+1100 [INFO] :: flapjack-jabber :: sending to group chat: what do you mean, 'test notifications for foo.xyz.dom'? Type 'help' for a list of acceptable commands.
2013-01-03T09:43:49+1100 [INFO] :: flapjack-jabber :: sending to group chat: found 1 entity matching /foo/ ... 
foo.xyz.dom
2013-01-03T09:43:49+1100 [WARN] :: flapjack-jabber :: disconnect handler called
2013-01-03T09:43:49+1100 [WARN] :: flapjack-jabber :: jabbers disconnected! reconnecting after a short deley ...
/opt/rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/blather-0.8.0/lib/blather/stream.rb:197:in `unbind': Blather::Stream::ConnectionFailed (Blather::Stream::ConnectionFailed)
        from /opt/rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/eventmachine-1.0.0/lib/eventmachine.rb:1435:in `event_callback'
        from /opt/rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in `run_machine'
        from /opt/rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in `run'
        from /opt/rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/em-synchrony-1.0.2/lib/em-synchrony.rb:28:in `synchrony'
        from /opt/rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/flapjack-0.6.60/lib/flapjack/coordinator.rb:38:in `start'
        from /opt/rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/flapjack-0.6.60/bin/flapjack:78:in `block in <top (required)>'
        from /opt/rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/flapjack-0.6.60/bin/flapjack:123:in `call'
        from /opt/rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/flapjack-0.6.60/bin/flapjack:123:in `block in <top (required)>'
        from /opt/rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/dante-0.1.5/lib/dante/runner.rb:112:in `call'
        from /opt/rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/dante-0.1.5/lib/dante/runner.rb:112:in `start'
        from /opt/rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/dante-0.1.5/lib/dante/runner.rb:87:in `block in daemonize'
        from /opt/rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/dante-0.1.5/lib/dante/runner.rb:80:in `fork'
        from /opt/rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/dante-0.1.5/lib/dante/runner.rb:80:in `daemonize'
        from /opt/rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/dante-0.1.5/lib/dante/runner.rb:72:in `execute'
        from /opt/rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/flapjack-0.6.60/bin/flapjack:122:in `<top (required)>'
        from /opt/rbenv/versions/1.9.3-p125/bin/flapjack:23:in `load'
        from /opt/rbenv/versions/1.9.3-p125/bin/flapjack:23:in `<main>'
Starting flapjack service...
2013-01-03T09:44:02+1100 [INFO] :: flapjack-executive :: Booting main loop.
...
2013-01-03T09:44:03+1100 [INFO] :: flapjack-jabber :: Jabber Connected
2013-01-03T09:44:03+1100 [INFO] :: flapjack-jabber :: Joining room log@conference.jabber.xyz.dom
2013-01-03T09:44:03+1100 [INFO] :: flapjack-jabber :: Joining room flapjack-oobetet@conference.jabber.xyz.dom
2013-01-03T09:44:03+1100 [INFO] :: flapjack-jabber :: sending to group chat: commands: 
  ACKID <id> <comment> [duration: <time spec>] 
  find entities matching /pattern/ 
  test notifications for <entity>[:<check>] 
  identify 
  help 

2013-01-03T09:44:03+1100 [INFO] :: flapjack-jabber :: sending to group chat: what do you mean, 'test notifications for foo.xyz.dom'? Type 'help' for a list of acceptable commands.
2013-01-03T09:44:03+1100 [INFO] :: flapjack-jabber :: sending to group chat: Flapjack 0.6.60 process 23968 on flapjack.xyz.dom 
Boot time: 2013-01-03 09:44:02 +1100
User CPU Time: 2.31
System CPU Time: 0.34
Linux flapjack 3.2.0-23-generic #36-Ubuntu SMP Tue Apr 10 20:39:51 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux
...
2013-01-03T09:44:03+1100 [INFO] :: flapjack-jabber :: sending to group chat: showing first 30 of 255 entities found matching /.*/
...
```

**Comment by jessereynolds** [comment]
@ali-graham decided not to proceed with #178 as it was deemed too hacky. 

We are not going to address this problem in 1.0. Closing.
