### ISSUE TITLE
Error uninstalling flapjack 1.3.0rc1 - Error generating or dispatching SMS Nexmo message

### ISSUE THREAD

**Issue by Hobbsee** [flapjack/flapjack#789]
```
Stopping flapjack
Flapjack stopping...Stopped PID: 143 at /var/run/flapjack/flapjack.pid
 done.
waiting for a max of 30 seconds for process 143 to exit.flapjack[143]: 2015-02-13T07:54:04+00:00 [ERROR] :: flapjack-sms_nexmo :: Error generating or dispatching SMS Nexmo message: TypeError: no implicit conversion of nil into String
/opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-1.3.0rc1/lib/flapjack/data/alert.rb:59:in `update'
/opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-1.3.0rc1/lib/flapjack/data/alert.rb:59:in `digest'
/opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-1.3.0rc1/lib/flapjack/data/alert.rb:59:in `initialize'
/opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-1.3.0rc1/lib/flapjack/data/alert.rb:133:in `new'
/opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-1.3.0rc1/lib/flapjack/data/alert.rb:133:in `next'
/opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-1.3.0rc1/lib/flapjack/gateways/sms_nexmo.rb:48:in `start'
/opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-1.3.0rc1/lib/flapjack/pikelet.rb:126:in `block in start'
flapjack[143]: 2015-02-13T07:54:04+00:00 [ERROR] :: flapjack-processor :: Invalid event data received, Event hash has missing keys 'state', 'entity', 'check' {"type"=>"noop"}
```

**Comment by Hobbsee** [comment]
Disabled sms_nexmo from being enabled by default.
