### ISSUE TITLE
1.3.0: uncaught exception in Event#initialize: invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by jessereynolds** [flapjack/flapjack#801]
This is causing flapjack to crash. 

```
/opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-1.3.0/lib/flapjack/data/event.rb:240:in `strip': invalid byte sequence in UTF-8 (Arg
umentError)
        from /opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-1.3.0/lib/flapjack/data/event.rb:240:in `initialize'
        from /opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-1.3.0/lib/flapjack/data/event.rb:135:in `new'
        from /opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-1.3.0/lib/flapjack/data/event.rb:135:in `next'
        from /opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-1.3.0/lib/flapjack/processor.rb:98:in `start'
        from /opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-1.3.0/lib/flapjack/pikelet.rb:126:in `block in start'
```

**Comment by jessereynolds** [comment]
Could be related to https://github.com/flapjack/flapjack/issues/514

**Comment by ali-graham** [comment]
There should be some way to set the encodings up to prevent things from crashing (even if the environmental settings are invalid for the received data), but there's probably a fair bit of experimentation involved in discerning what that way is.

**Comment by jessereynolds** [comment]
At a minimum lets rescue this exception and log the living daylights out of it.

**Comment by jessereynolds** [comment]
Seems like most cases are mitigated with #805
