### ISSUE TITLE
Flapjack from address is marked as optional, but crashes if it isn't set

### ISSUE THREAD

**Issue by Hobbsee** [flapjack/flapjack#817]
From the default config file in 1.x:

```
      # these values are passed directly through to EventMachine::Protocols::SmtpClient configuration,
      # and can be omitted if the defaults are acceptable
      smtp_config:
        # from: "Flapjack Example <flapjack@noreply.example>"
```

However, if you just enable the email gateway, without uncommenting this from address, sending email fails with the following:

```
2015-03-10T17:51:40.695439-07:00 [INFO] :: flapjack-processor :: Generating notification for event foo-app-01:HTTP, service, critical, Simulated check output (test by operator), 2015-03-10 17:51:40 -0700
2015-03-10T17:51:40.702554-07:00 [INFO] :: flapjack-notifier :: Enqueueing email alert for foo-app-01:HTTP to test@test.com type: problem rollup: -
2015-03-10T17:51:40.705231-07:00 [ERROR] :: flapjack-email :: Error generating or delivering email to test@test.com: TypeError: can't clone NilClass
2015-03-10T17:51:40.705406-07:00 [ERROR] :: flapjack-email :: /opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-1.3.0/lib/flapjack/gateways/email.rb:86:in `clone'
/opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-1.3.0/lib/flapjack/gateways/email.rb:86:in `deliver'
/opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-1.3.0/lib/flapjack/gateways/email.rb:55:in `start'
/opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-1.3.0/lib/flapjack/pikelet.rb:126:in `block in start'
2015-03-10T17:51:40.705507-07:00 [ERROR] :: flapjack-email :: Error generating or dispatching email message: TypeError: can't clone NilClass
/opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-1.3.0/lib/flapjack/gateways/email.rb:86:in `clone'
/opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-1.3.0/lib/flapjack/gateways/email.rb:86:in `deliver'
/opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-1.3.0/lib/flapjack/gateways/email.rb:55:in `start'
/opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-1.3.0/lib/flapjack/pikelet.rb:126:in `block in start'
```

**Comment by moises-silva** [comment]
@SarahKowalik I stumbled upon this issue today while testing flapjack for the first time. It seems the issue was addressed (intentionally or as a side-effect of some other code changing) in master. I've back-ported the fix to maint/1.x (see pull request above). That should fix the problem.
