### ISSUE TITLE
Continuous crash with RegexpError

### ISSUE THREAD

**Issue by dwagon** [flapjack/flapjack#819]
With flapjack  1.3.0_0.20150217225632.el6 under CentOS 6.5

After adding a bad regexp for notification flapjack crashed. Every time I restart it flapjack crashes again. This makes it impossible to remove / update the notification rules.

Any assistance would be really appreciated.

```
/opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-1.3.0/lib/flapjack/data/notification_rule.rb:136:in `block in match_regex_entities?': target of repeat operator is not specified: /*/ (RegexpError)
	from /opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-1.3.0/lib/flapjack/data/notification_rule.rb:135:in `each'
	from /opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-1.3.0/lib/flapjack/data/notification_rule.rb:135:in `match_regex_entities?'
	from /opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-1.3.0/lib/flapjack/data/notification.rb:155:in `block (2 levels) in messages'
	from /opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-1.3.0/lib/flapjack/data/notification.rb:144:in `select'
	from /opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-1.3.0/lib/flapjack/data/notification.rb:144:in `block in messages'
	from /opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-1.3.0/lib/flapjack/data/notification.rb:129:in `collect'
	from /opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-1.3.0/lib/flapjack/data/notification.rb:129:in `messages'
	from /opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-1.3.0/lib/flapjack/notifier.rb:106:in `process_notification'
	from /opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-1.3.0/lib/flapjack/notifier.rb:69:in `start'
	from /opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-1.3.0/lib/flapjack/pikelet.rb:126:in `block in start'
```

**Comment by ali-graham** [comment]
We should definitely be catching that; until that's dealt with, you can probably disable the notifier component in the config file (as that's the only part applying the rules), start Flapjack, use the API to delete the offending rule, stop Flapjack, revert the config file, and restart and continue as normal.

**Comment by dwagon** [comment]
That worked perfectly - Thanks

**Comment by ali-graham** [comment]
Fixed in https://github.com/flapjack/flapjack/releases/tag/v1.5.0 .
