### ISSUE TITLE
master: flapjack fails to start after package install

### ISSUE THREAD

**Issue by jessereynolds** [flapjack/flapjack#826]
From build log: http://is.gd/vJcQO7

```
/opt/flapjack/embedded/lib/ruby/site_ruby/2.1.0/rubygems/custom_require.rb:36:in `require': cannot load such file -- zermelo/records/redis_record (LoadError)
	from /opt/flapjack/embedded/lib/ruby/site_ruby/2.1.0/rubygems/custom_require.rb:36:in `require'
	from /opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-2.0.0a1/lib/flapjack/data/contact.rb:9:in `<top (required)>'
	from /opt/flapjack/embedded/lib/ruby/site_ruby/2.1.0/rubygems/custom_require.rb:36:in `require'
	from /opt/flapjack/embedded/lib/ruby/site_ruby/2.1.0/rubygems/custom_require.rb:36:in `require'
	from /opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-2.0.0a1/lib/flapjack/cli/import.rb:6:in `<top (required)>'
	from /opt/flapjack/embedded/lib/ruby/site_ruby/2.1.0/rubygems/custom_require.rb:36:in `require'
	from /opt/flapjack/embedded/lib/ruby/site_ruby/2.1.0/rubygems/custom_require.rb:36:in `require'
	from /opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/gli-2.12.0/lib/gli/app.rb:308:in `block in load_commands'
	from /opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/gli-2.12.0/lib/gli/app.rb:305:in `each'
	from /opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/gli-2.12.0/lib/gli/app.rb:305:in `load_commands'
	from /opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/gli-2.12.0/lib/gli/app.rb:38:in `block in commands_from'
	from /opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/gli-2.12.0/lib/gli/app.rb:36:in `each'
	from /opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/gli-2.12.0/lib/gli/app.rb:36:in `commands_from'
	from /opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-2.0.0a1/bin/flapjack:10:in `<top (required)>'
	from /opt/flapjack/bin/flapjack:23:in `load'
	from /opt/flapjack/bin/flapjack:23:in `<main>'
```

Two packages that appear to exhibit this are Centos 6 and Ubuntu Trusty:

http://packages.flapjack.io/tmp/flapjack-2.0.0_0.20150317095414a1.el6-1.el6.x86_64.rpm
http://packages.flapjack.io/tmp/flapjack_2.0.0~a1~20150317102732~master~trusty-1_amd64.deb

**Comment by jessereynolds** [comment]
Perhaps this is a problem with the init scripts that are brought into the package from the omnibus-flapjack repo.

**Comment by Hobbsee** [comment]
This is the same as https://github.com/flapjack/flapjack/issues/757

**Comment by ali-graham** [comment]
Closing, duplicate.
