### ISSUE TITLE
SNS Notification Failing

### ISSUE THREAD

**Issue by mholtrlc** [flapjack/flapjack#829]
I'm having issues with getting the SNS Notification working.

Flapjack.log
````
2015-04-03T15:12:20.977744-07:00 [INFO] :: flapjack-processor :: Generating notification for event sensu.rlcit.org:iostat_metrics, service, critical, Check failed to run: No such file or directory - iostat -x 1 2, ["/etc/sensu/plugins/system/iostat-extended-metrics.rb:108:in ``'", "/etc/sensu/plugins/system/iostat-extended-metrics.rb:108:in `run'", "/var/lib/gems/1.9.1/gems/sensu-plugin-1.1.0/lib/sensu-plugin/cli.rb:56:in `block in <class:CLI>'"], 2015-04-03 15:12:20 -0700
2015-04-03T15:12:20.994811-07:00 [INFO] :: flapjack-notifier :: Enqueueing email alert for sensu.rlcit.org:iostat_metrics to  type: problem rollup: -
2015-04-03T15:12:20.995494-07:00 [INFO] :: flapjack-notifier :: Enqueueing sns alert for sensu.rlcit.org:iostat_metrics to arn:aws:sns:us-east-1:535547360713:rlc-monitoring type: problem rollup: -
2015-04-03T15:12:21.165150-07:00 [ERROR] :: flapjack-sns :: Failed to send notification via SNS, response status is 403, notification_id: 28451200-1428099140.995425
````

flapjack_config.yaml
````sns:
      enabled: yes
      queue: sns_notifications
      region_name: us-east-1
      # Don't forget to use an IAM user's credentials here so revocation is easy!
      access_key: SOMEACCESSKEY
      secret_key: SOMESECRETKEY
````

Contact SNS Media
````
arn:aws:sns:us-east-1:stringofnumbers:topic-name
````

am I missing something?

**Comment by xcxsxvx** [comment]
I had the same problem. I believe it's because spaces were being encoded as +'s, which amazon does not like. 
I submitted a PR.

**Comment by jessereynolds** [comment]
Please try 1.6.0 when it comes out, or 1.6.0rc2 and re-open if you're still having issues. Thank you

**Comment by mholtrlc** [comment]
how do I go about installing 1.6.0rc2?

**Comment by mholtrlc** [comment]
I've installed 1.6.0rc2 and am still having this issue.

````
2015-05-18T11:46:49.164303-07:00 [INFO] :: flapjack-notifier :: Enqueueing sns alert for unifi:unifi_check to arn:aws:sns:us-east-1:535547360713:rlc-monitoring type: problem rollup: -
2015-05-18T11:46:49.354114-07:00 [ERROR] :: flapjack-sns :: Failed to send notification via SNS, response status is 403, notification_id: 32078680-1431974809.164207
````
I have given the IAM user the AmazonSNSFullAccess policy as well.

**Comment by jessereynolds** [comment]
Could you set the flapjack sns gateway to debug logging level and send through the (obfuscated) logs of a failure?

**Comment by mholtrlc** [comment]
Here's the flapjack.log:
````
2015-05-18T13:48:36.547841-07:00 [INFO] :: flapjack-coordinator :: Checking for orphaned entity ids...
2015-05-18T13:48:36.548459-07:00 [INFO] :: flapjack-coordinator :: Finished checking for orphaned entity ids.
2015-05-18T13:48:36.550576-07:00 [INFO] :: flapjack-processor :: Checking for orphaned entity ids...
2015-05-18T13:48:36.550970-07:00 [INFO] :: flapjack-processor :: Finished checking for orphaned entity ids.
2015-05-18T13:48:36.553206-07:00 [INFO] :: flapjack-processor :: Checking for orphaned entity ids...
2015-05-18T13:48:36.553611-07:00 [INFO] :: flapjack-processor :: Finished checking for orphaned entity ids.
2015-05-18T13:48:36.569744-07:00 [INFO] :: flapjack-processor :: Booting main loop.
2015-05-18T13:48:36.571303-07:00 [INFO] :: flapjack-notifier :: Checking for orphaned entity ids...
2015-05-18T13:48:36.572165-07:00 [INFO] :: flapjack-notifier :: Finished checking for orphaned entity ids.
2015-05-18T13:48:36.576692-07:00 [INFO] :: flapjack-notifier :: Checking for orphaned entity ids...
2015-05-18T13:48:36.578257-07:00 [INFO] :: flapjack-notifier :: Finished checking for orphaned entity ids.
2015-05-18T13:48:36.583924-07:00 [INFO] :: flapjack-notifier :: Booting main loop.
2015-05-18T13:48:36.585717-07:00 [INFO] :: flapjack-sns :: Checking for orphaned entity ids...
2015-05-18T13:48:36.586461-07:00 [INFO] :: flapjack-sns :: Finished checking for orphaned entity ids.
2015-05-18T13:48:36.588623-07:00 [INFO] :: flapjack-sns :: starting
2015-05-18T13:48:36.588718-07:00 [DEBUG] :: flapjack-sns :: new aws_sns gateway pikelet with the following options: {"enabled"=>true, "queue"=>"sns_notifications", "region_name"=>"us-east-1", "logger"=>{"level"=>"DEBUG", "syslog_errors"=>true}, "access_key"=>"[access_key]", "secret_key"=>"[secret_key]"}
2015-05-18T13:48:36.588815-07:00 [DEBUG] :: flapjack-sns :: aws_sns gateway is going into blpop mode on sns_notifications
2015-05-18T13:48:36.597337-07:00 [INFO] :: flapjack-web :: Checking for orphaned entity ids...
2015-05-18T13:48:36.598093-07:00 [INFO] :: flapjack-web :: Finished checking for orphaned entity ids.
2015-05-18T13:48:36.601496-07:00 [INFO] :: flapjack-web :: Checking for orphaned entity ids...
2015-05-18T13:48:36.602280-07:00 [INFO] :: flapjack-web :: Finished checking for orphaned entity ids.
2015-05-18T13:48:36.604123-07:00 [INFO] :: flapjack-web :: starting web - class
2015-05-18T13:48:36.605249-07:00 [INFO] :: flapjack-web :: base_url is not configured, setting to '/'
2015-05-18T13:48:36.609076-07:00 [INFO] :: flapjack-jsonapi :: Checking for orphaned entity ids...
2015-05-18T13:48:36.610350-07:00 [INFO] :: flapjack-jsonapi :: Finished checking for orphaned entity ids.
2015-05-18T13:48:36.613646-07:00 [INFO] :: flapjack-jsonapi :: Checking for orphaned entity ids...
2015-05-18T13:48:36.614637-07:00 [INFO] :: flapjack-jsonapi :: Finished checking for orphaned entity ids.
2015-05-18T13:48:36.616684-07:00 [INFO] :: flapjack-jsonapi :: starting jsonapi - class
2015-05-18T13:48:36.649836-07:00 [INFO] :: flapjack-processor :: Generating notification for event ems.reallifechurch.org:ems_database_check, service, critical, CheckWinService CRITICAL: MSSQL$EMS1 is not running, 2015-05-18 13:47:43 -0700
2015-05-18T13:48:43.990984-07:00 [INFO] :: flapjack-web :: POST /acknowledgements/ems.reallifechurch.org/ems_database_check acknowledgement_id=e7eec803&summary=&duration=2+hours
2015-05-18T13:48:44.002368-07:00 [INFO] :: flapjack-processor :: Generating notification for event ems.reallifechurch.org:ems_database_check, action, acknowledgement, , 2015-05-18 13:48:43 -0700
2015-05-18T13:48:44.007696-07:00 [INFO] :: flapjack-notifier :: Enqueueing sns alert for ems.reallifechurch.org:ems_database_check to arn:aws:sns:us-east-1:[id][topic_name] type: acknowledgement rollup: -
2015-05-18T13:48:44.021942-07:00 [INFO] :: flapjack-web :: GET /check?entity=ems.reallifechurch.org&check=ems_database_check
2015-05-18T13:48:44.183301-07:00 [DEBUG] :: flapjack-sns :: server response: <ErrorResponse xmlns="http://sns.amazonaws.com/doc/2010-03-31/">
  <Error>
    <Type>Sender</Type>
    <Code>SignatureDoesNotMatch</Code>
    <Message>The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.</Message>
  </Error>
  <RequestId>c2f8ac3d-9b2a-59cc-9bb0-e1e9c946281d</RequestId>
</ErrorResponse>

2015-05-18T13:48:44.183489-07:00 [ERROR] :: flapjack-sns :: Failed to send notification via SNS, response status is 403, notification_id: 43063200-1431982124.7593
2015-05-18T13:48:44.183625-07:00 [DEBUG] :: flapjack-sns :: aws_sns gateway is going into blpop mode on sns_notifications
````

**Comment by mholtrlc** [comment]
additional notes,

Policy for IAM User:
````
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Stmt1431981442000",
            "Effect": "Allow",
            "Action": [
                "sns:*"
            ],
            "Resource": [
                "arn:aws:sns:us-east-1:[id]:[topic-name]"
            ]
        }
    ]
}
````

flapjack_config.yaml
````
production:
  pid_dir: /var/run/flapjack/
  log_dir: /var/log/flapjack/
  daemonize: yes
  logger:
    level: INFO
    syslog_errors: yes
  redis:
    host: 127.0.0.1
    port: 6380
    db: 0
  # Processes monitoring events off the *events* queue (a redis list) and decides
  # what actions to take (generate notification event, record state changes, etc)
  processor:
    enabled: yes
    queue: events
    notifier_queue: notifications
    archive_events: true
    events_archive_maxage: 10800
    # Flapjack sets scheduled maintenance on new check results so contacts aren't
    # notified as soon as Flapjack becomes aware of an entity to notify on.
    # This is useful is cases where your monitoring starts checking something
    # before it is completely provisioned
    # Value parsed by https://github.com/hpoydar/chronic_duration
    # You can disable this setting by specifying 0 seconds.
    new_check_scheduled_maintenance_duration: 100 years
    new_check_scheduled_maintenance_ignore_tags:
      - bypass_ncsm
    logger:
      level: INFO
      syslog_errors: yes
  # Processes notification events off the *notifications* queue (a redis list) and
  # works out who to notify, and on which media, and with what kind of notification
  # message. It then creates jobs for the various notification gateways below.
  notifier:
    enabled: yes
    queue: notifications
    email_queue: email_notifications
    sms_queue: sms_notifications
    sms_twilio_queue: sms_twilio_notifications
    sns_queue: sns_notifications
    jabber_queue: jabber_notifications
    pagerduty_queue: pagerduty_notifications
    notification_log_file: /var/log/flapjack/notification.log
    default_contact_timezone: UTC
    logger:
      level: INFO
      syslog_errors: yes
  nagios-receiver:
    fifo: "/var/cache/nagios3/event_stream.fifo"
    pid_dir: "/var/run/flapjack/"
    log_dir: "/var/log/flapjack/"
  nsca-receiver:
    fifo: "/var/lib/nagios3/rw/nagios.cmd"
    pid_dir: "/var/run/flapjack/"
    log_dir: "/var/log/flapjack/"
  gateways:
    # Generates email notifications
    email:
      enabled: no
      # the redis queue this pikelet will look for notifications on
      queue: email_notifications
      logger:
        level: INFO
        syslog_errors: yes
      # these values are passed directly through to EventMachine::Protocols::SmtpClient configuration,
      # and can be omitted if the defaults are acceptable
      smtp_config:
        # from: "Flapjack Example <flapjack@noreply.example>"
        # reply_to: "flapjack@support.example"
        host: 127.0.0.1
        # 1025 is the default port for http://mailcatcher.me
        port: 1025
        starttls: false
        #auth:
        #  type:
        #  username:
        #  password:
      # location of custom alert templates
      #templates:
      #  rollup_subject.text: '/etc/flapjack/templates/email/rollup_subject.text.erb'
      #  alert_subject.text: '/etc/flapjack/templates/email/alert_subject.text.erb'
      #  rollup.text: '/etc/flapjack/templates/email/rollup.text.erb'
      #  alert.text: '/etc/flapjack/templates/email/alert.text.erb'
      #  rollup.html: '/etc/flapjack/templates/email/rollup.html.erb'
      #  alert.html: '/etc/flapjack/templates/email/alert.html.erb'
    # Sends SMS notifications via MessageNet (Australia only)
    sms:
      enabled: no
      # the redis queue this pikelet will look for notifications on
      queue: sms_notifications
      endpoint: 'https://www.messagenet.com.au/dotnet/Lodge.asmx/LodgeSMSMessage'
      username: "ermahgerd"
      password: "xxxx"
      logger:
        level: INFO
        syslog_errors: yes
      # location of custom alert templates
      #templates:
      #  rollup.text: '/etc/flapjack/templates/sms/rollup.text.erb'
      #  alert.text: '/etc/flapjack/templates/sms/alert.text.erb'
    # Sends SMS notifications via Twilio
    sms_twilio:
      enabled: no
      queue: sms_twilio_notifications
      account_sid: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      auth_token: "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy"
      from: "+1xxxxxxxxxx"
      logger:
        level: INFO
        syslog_errors: yes
      # location of custom alert templates
      # location of custom alert templates
      #templates:
      #  rollup.text: '/etc/flapjack/templates/sms_twilio/rollup.text.erb'
      #  alert.text: '/etc/flapjack/templates/sms_twilio/alert.text.erb'
    # Generates SNS notifications
    sns:
      enabled: yes
      queue: sns_notifications
      region_name: us-east-1
      logger:
        level: DEBUG
        syslog_errors: yes
      # Don't forget to use an IAM user's credentials here so revocation is easy!
      access_key: [access_key]
      secret_key: [secret_key]
    # Connects to an XMPP (jabber) server, sends notifications (to rooms and individuals),
    # handles acknowledgements from jabber users and other commands.
    jabber:
      enabled: no
      # the redis queue this pikelet will look for notifications on
      queue: jabber_notifications
      server: "jabber.example.com"
      port: 5222
      jabberid: "flapjack@jabber.example.com"
      password: "good-password"
      alias: "flapjack"
      # List of strings that this pikelet user will respond to
      identifiers:
        - "@flapjack"
      # the Multi-User Chats the pikelet should join and announce to
      rooms:
        - "gimp@conference.jabber.example.com"
        - "log@conference.jabber.example.com"
      logger:
        level: INFO
        syslog_errors: yes
      # location of custom alert templates
      #templates:
      #  rollup.text: '/etc/flapjack/templates/jabber/rollup.text.erb'
      #  alert.text: '/etc/flapjack/templates/jabber/alert.text.erb'
    # Sends notifications to and accepts acknowledgements from [PagerDuty](http://www.pagerduty.com/)
    # (NB: contacts will need to have a registered PagerDuty account to use this)
    pagerduty:
      enabled: no
      # the redis queue this pikelet will look for notifications on
      queue: pagerduty_notifications
      logger:
        level: INFO
        syslog_errors: yes
      # location of custom alert templates
      #templates:
      #  alert.text: '/etc/flapjack/templates/pagerduty/alert.text.erb'
    # Browsable web interface
    web:
      enabled: yes
      port: 3080
      timeout: 300
      # Seconds between auto_refresh of entities/checks pages.  Set to 0 to disable
      auto_refresh: 120
      access_log: "/var/log/flapjack/web_access.log"
      api_url: "http://10.10.11.14:3081/"
      # Full path to location of logo file, e.g. /etc/flapjack/custom_logo.png
      #logo_image_path: "/etc/flapjack/web/custom_logo/flapjack-2013-notext-transparent-300-300.png"
      logger:
        level: INFO
        syslog_errors: yes
    # HTTP API server
    jsonapi:
      enabled: yes
      port: 3081
      timeout: 300
      access_log: "/var/log/flapjack/jsonapi_access.log"
      base_url: "http://10.10.11.14:3081/"
      logger:
        level: INFO
        syslog_errors: yes
    # "out-of-band" end-to-end testing, used for monitoring other instances of
    # flapjack to ensure that they are running correctly
    oobetet:
      enabled: no
      server: "jabber.example.com"
      port: 5222
      # jabberid, password, alias, rooms: see the jabber pikelet
      jabberid: "flapjacktest@jabber.example.com"
      password: "nuther-good-password"
      alias: "flapjacktest"
      # The check oobetet should watch for the state change
      watched_check: "PING"
      # The entitiy that the check should be associated with
      watched_entity: "foo.example.com"
      # The maximum amount of time allowed to pass between state changes on that check
      max_latency: 300
      # The API key for a service in PagerDuty that the oobetet will use to alert you
      pagerduty_contact: "11111111111111111111111111111111"
      # Jabber rooms to join
      rooms:
        - "flapjacktest@conference.jabber.example.com"
        - "gimp@conference.jabber.example.com"
        - "log@conference.jabber.example.com"
      logger:
        level: INFO
        syslog_errors: yes
````

**Comment by jessereynolds** [comment]
This seems to be the best pointer towards the cause of the problem:

SignatureDoesNotMatch

The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

Looks like we are calculating the request signature incorrectly.

**Comment by ali-graham** [comment]
On 19/05/2015 8:24 am, Jesse Reynolds wrote:

> Looks like we are calculating the request signature incorrectly.

I'll have another look at that code, and see if I can find some code 
examples elsewhere to compare and see what we might be doing wrong.

**Comment by ali-graham** [comment]
One thing I see in http://docs.aws.amazon.com/general/latest/gr/signature-version-2.html is that "hexadecimal characters must be uppercased", which would apply to the `AWSAccessKeyId` query field used for signing.

**Comment by ali-graham** [comment]
Enforced that and escaped query keys in https://github.com/flapjack/flapjack/commit/0bba1176a82f7884770bd98372e0e2a4b53d1a2f ; I can't really see that fixing anything, but it looks like the right thing to do.

**Comment by mholtrlc** [comment]
I just applied the patch and still got the same error

**Comment by ali-graham** [comment]
Hi @mholtrlc , can I get you to try this patch directly? https://gist.github.com/ali-graham/113ea592586b9e1d8b5f

The docs say "The resulting signature must be base-64 encoded and then URI encoded", and I don't think we've been doing that last part.

**Comment by mholtrlc** [comment]
I just left the office for the day but I'll give it a try in the morning
and get back to you

On Monday, May 18, 2015, Ali Graham <notifications@github.com> wrote:

> Hi @mholtrlc <https://github.com/mholtrlc> , can I get you to try this
> patch directly? https://gist.github.com/ali-graham/113ea592586b9e1d8b5f
>
> The docs say "The resulting signature must be base-64 encoded and then URI
> encoded", and I don't think we've been doing that last part.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flapjack/flapjack/issues/829#issuecomment-103285937>.
>


-- 

[image: Real Life Church] <http://www.reallifechurch.org>

Michael Holt / IT Administrator
(661) 705-4711/ mholt@reallifechurch.org

Real Life Church Office: (661) 775-7401
23841 Newhall Ranch Rd
Valencia, CA 91355
http://www.reallifechurch.org

This e-mail message may contain confidential or legally privileged
information and is intended only for the use of the intended recipient(s).
Any unauthorized disclosure, dissemination, distribution, copying or the
taking of any action in reliance on the information herein is prohibited.
E-mails are not secure and cannot be guaranteed to be error free as they
can be intercepted, amended, or contain viruses. Anyone who communicates
with us by e-mail is deemed to have accepted these risks. Company Name is
not responsible for errors or omissions in this message and denies any
responsibility for any damage arising from the use of e-mail. Any opinion
and other statement contained in this message and any attachment are solely
those of the author and do not necessarily represent those of the company.

**Comment by mholtrlc** [comment]
still getting the same error

**Comment by mholtrlc** [comment]
I spent a few hours tonight playing with it and resolved the issue.  The issue appeared to be with improper encoding of the URL string for generating the signature.  I'll send a pull request shortly with the updated code I have.

**Comment by jessereynolds** [comment]
This issue is present in 1.5.0. It's still going to be an issue for the 1.6.0 release as nobody has managed to fix this yet and we need to cut a release. Hopefully someone has time to resolve this for a 1.6 point release.
