### ISSUE TITLE
Ctrl+c fails when attempting to stop the --no-daemonize version of flapjack master

### ISSUE THREAD

**Issue by Hobbsee** [flapjack/flapjack#846]
Realising I forgot to start redis first, I tried to ctrl+c flapjack a number of times, but nothing happens.  I then have to kill -9 the process id.

This isn't great - is this something we can fix?

```
flapjack ➤ GLI_DEBUG=true bundle exec bin/flapjack --config etc/flapjack_config.toml server start --no-daemonize                                                                                                             (master|✔)
Flapjack starting...
2015-05-05T16:35:19.219305+10:00 [INFO] :: flapjack-processor :: Booting main loop.
2015-05-05T16:35:19.222219+10:00 [INFO] :: flapjack-jsonapi :: starting jsonapi - class
2015-05-05T16:35:19.223604+10:00 [WARN] :: flapjack-processor :: Redis::CannotConnectError Error connecting to Redis on 127.0.0.1:6380 (Errno::ECONNREFUSED)
2015-05-05T16:35:19.224348+10:00 [WARN] :: flapjack-notifier :: Redis::CannotConnectError Error connecting to Redis on 127.0.0.1:6380 (Errno::ECONNREFUSED)
2015-05-05T16:35:19.224491+10:00 [INFO] :: flapjack-web :: starting web - class
2015-05-05T16:35:19.226595+10:00 [WARN] :: flapjack-notifier :: /Users/sarah/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:331:in `rescue in establish_connection'
/Users/sarah/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:317:in `establish_connection'
/Users/sarah/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:94:in `block in connect'
/Users/sarah/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:279:in `with_reconnect'
/Users/sarah/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:93:in `connect'
/Users/sarah/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:350:in `ensure_connected'
/Users/sarah/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:207:in `block in process'
/Users/sarah/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:292:in `logging'
/Users/sarah/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:206:in `process'
/Users/sarah/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:112:in `call'
/Users/sarah/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis.rb:109:in `block in quit'
/Users/sarah/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis.rb:37:in `block in synchronize'
/Users/sarah/.rbenv/versions/2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/sarah/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis.rb:37:in `synchronize'
/Users/sarah/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis.rb:107:in `quit'
/Users/sarah/src/flpjck/flapjack/lib/flapjack/redis_proxy.rb:33:in `quit'
/Users/sarah/src/flpjck/flapjack/lib/flapjack/notifier.rb:58:in `ensure in start'
/Users/sarah/src/flpjck/flapjack/lib/flapjack/notifier.rb:58:in `start'
/Users/sarah/src/flpjck/flapjack/lib/flapjack/pikelet.rb:146:in `block in start'
/Users/sarah/src/flpjck/flapjack/lib/flapjack/pikelet.rb:73:in `block (2 levels) in start'
/Users/sarah/src/flpjck/flapjack/lib/flapjack/pikelet.rb:70:in `loop'
/Users/sarah/src/flpjck/flapjack/lib/flapjack/pikelet.rb:70:in `block in start'
2015-05-05T16:35:19.226675+10:00 [WARN] :: flapjack-processor :: /Users/sarah/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:331:in `rescue in establish_connection'
/Users/sarah/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:317:in `establish_connection'
/Users/sarah/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:94:in `block in connect'
/Users/sarah/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:279:in `with_reconnect'
/Users/sarah/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:93:in `connect'
/Users/sarah/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:350:in `ensure_connected'
/Users/sarah/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:207:in `block in process'
/Users/sarah/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:292:in `logging'
/Users/sarah/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:206:in `process'
/Users/sarah/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:112:in `call'
/Users/sarah/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis.rb:109:in `block in quit'
/Users/sarah/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gemlog writing failed. Flapjack::PikeletStop
^C^C^C
^C
^C^C
```

**Comment by ali-graham** [comment]
This may be due to failing in the pikelets before they get to the main (signal-interruptible) loop. We can probably work around this by being a bit more paranoid with the connection attempts, and then letting execution continue to the extent possible until it reaches that interruptible point. I'll take a look.

**Comment by Hobbsee** [comment]
This is still failing - I neglected to start redis on the correct port, and received the following stacktrace:  https://gist.github.com/b32ba7110908188cd7fb

Ctrl+c did not work to stop this process running.

**Comment by Hobbsee** [comment]
Errno::EINVAL is now behaving the same as Redis::CannotConnectError, and neither of them are working with ctrl+c.

**Comment by Hobbsee** [comment]
This is happening most of the time - but sometimes, it stops correctly on it's own.

When it doesn't, here's the traceback:

```
Flapjack starting...
2015-05-12T14:16:12.074581+10:00 [INFO] :: flapjack-web :: starting web - class
2015-05-12T14:16:12.076466+10:00 [INFO] :: flapjack-processor :: Booting main loop.
2015-05-12T14:16:12.079404+10:00 [WARN] :: flapjack-processor :: Redis::CannotConnectError Error connecting to Redis on 127.0.0.1:6380 (Errno::ECONNREFUSED)
2015-05-12T14:16:12.079624+10:00 [INFO] :: flapjack-jsonapi :: starting jsonapi - class
2015-05-12T14:16:12.079941+10:00 [WARN] :: flapjack-notifier :: Redis::CannotConnectError Error connecting to Redis on 127.0.0.1:6380 (Errno::ECONNREFUSED)
2015-05-12T14:16:12.080030+10:00 [WARN] :: flapjack-notifier :: /Users/sarah/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:331:in `rescue in establish_connection'
/Users/sarah/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:317:in `establish_connection'
/Users/sarah/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:94:in `block in connect'
/Users/sarah/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:279:in `with_reconnect'
/Users/sarah/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:93:in `connect'
/Users/sarah/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:350:in `ensure_connected'
/Users/sarah/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:207:in `block in process'
/Users/sarah/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:292:in `logging'
/Users/sarah/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:206:in `process'
/Users/sarah/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:112:in `call'
/Users/sarah/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis.rb:191:in `block in info'
/Users/sarah/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis.rb:37:in `block in synchronize'
/Users/sarah/.rbenv/versions/2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/sarah/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis.rb:37:in `synchronize'
/Users/sarah/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis.rb:190:in `info'
/Users/sarah/src/flpjck/flapjack/lib/flapjack/redis_proxy.rb:49:in `proxied_connection'
/Users/sarah/src/flpjck/flapjack/lib/flapjack/redis_proxy.rb:39:in `method_missing'
/Users/sarah/src/flpjck/flapjack/lib/flapjack/record_queue.rb:20:in `foreach'
/Users/sarah/src/flpjck/flapjack/lib/flapjack/notifier.rb:52:in `block (2 levels) in start'
/Users/sarah/.rbenv/versions/2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/sarah/src/flpjck/flapjack/lib/flapjack/notifier.rb:51:in `block in start'
/Users/sarah/src/flpjck/flapjack/lib/flapjack/notifier.rb:50:in `loop'
/Users/sarah/src/flpjck/flapjack/lib/flapjack/notifier.rb:50:in `start'
/Users/sarah/src/flpjck/flapjack/lib/flapjack/pikelet.rb:146:in `block in start'
/Users/sarah/src/flpjck/flapjack/lib/flapjack/pikelet.rb:73:in `block (2 levels) in start'
/Users/sarah/src/flpjck/flapjack/lib/flapjack/pikelet.rb:70:in `loop'
/Users/sarah/src/flpjck/flapjack/lib/flapjack/pikelet.rb:70:in `block in start'
2015-05-12T14:16:12.080170+10:00 [WARN] :: flapjack-processor :: /Users/sarah/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:331:in `rescue in establish_connection'
/Users/sarah/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:317:in `establish_connection'
/Users/sarah/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:94:in `block in connect'
/Users/sarah/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:279:in `with_reconnect'
/Users/sarah/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:93:in `connect'
/Users/sarah/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:350:in `ensure_connected'
/Users/sarah/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:207:in `block in process'
/Users/sarah/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:292:in `logging'
/Users/sarah/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:206:in `process'
/Users/sarah/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:112:in `call'
/Users/sarah/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis.rb:191:in `block in info'
/Users/sarah/.rbenv/versilog writing failed. Flapjack::PikeletStop

^C^[[A^C
```

Perhaps the failed log writing is blocking the exit?

**Comment by ali-graham** [comment]
I can't replicate this, even with the log dir in the config changed to a non-existent directory name. Redis isn't running, and Flapjack exits normally with the `CannotConnectError`. Can you try disabling the logging statements at https://github.com/flapjack/flapjack/blob/86fabc3303d3d67f89eb55510904ed793cd9a2d5/lib/flapjack/pikelet.rb#L81-L83 and see if those are the ones causing the problem?

The `log writing failed` is sometimes seen when trying to write out log entries from within a signal handler, but we're signalling the main thread from within the handler to avoid that problem.
