### ISSUE TITLE
Delete Scheduled Maintenance Periods does not work with JSON API

### ISSUE THREAD

**Issue by damlub** [flapjack/flapjack#850]
Hi,

I use Flapjack 1.5.0 from rpm together with Sensu.

When trying to delete all scheduled maintenance periods follwing to the API documentation I get the error:
```
/opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-diner-1.3.0/lib/flapjack-diner/argument_validator.rb:22:in `validate': 'start_time' is required. (ArgumentError)
	from /opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-diner-1.3.0/lib/flapjack-diner/resources/maintenance_periods.rb:62:in `block (3 levels) in <module:MaintenancePeriods>'
	from /opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-diner-1.3.0/lib/flapjack-diner/tools.rb:108:in `instance_eval'
	from /opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-diner-1.3.0/lib/flapjack-diner/tools.rb:108:in `validate_params'
	from /opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-diner-1.3.0/lib/flapjack-diner/resources/maintenance_periods.rb:61:in `block (2 levels) in <module:MaintenancePeriods>'
```

What I try to do is cleaning all maintenances with:
```
entities.each do |entity|
  Flapjack::Diner.delete_scheduled_maintenances_entities(
    entity[:id],
    :end_time   => Time.now.iso8601
  )
end
```

using ```:start_time``` instead of ```:end_time``` does not return that error but does not work either.

Please also correct the documentation.
http://flapjack.io/docs/1.0/jsonapi/#delete-scheduled-maintenance-periods-on-entities

Thank you,
Damian

**Comment by hdoedens** [comment]
Hi @damlub I am also facing this issue. Have you been able to work around it?

**Comment by damlub** [comment]
Hi @hdoedens 
Great thanks for that!

Currently, I ended schedues maintenances the dirty way with Redis directly
$ redis-cli KEYS hostname-abc*maint* | xargs redis-cli DEL

cheers!
