### ISSUE TITLE
master: crash with PagerDuty gateway enabled - redis is nil in AckFinder 

### ISSUE THREAD

**Issue by jessereynolds** [flapjack/flapjack#857]
this is when running in the master branch @ e489df6220858092175655329913fb6869df7085, or 855_pagerduty_subdomain branch. 

```
$ flapjackdev server start --no-daemonize
Flapjack starting...
2015-05-11T21:50:11.526415+09:30 [DEBUG] :: flapjack-pagerduty-notifier :: pikelet start for Flapjack::Gateways::PagerDuty::Notifier
2015-05-11T21:50:11.528481+09:30 [INFO] :: flapjack-processor :: Booting main loop.
2015-05-11T21:50:11.530102+09:30 [DEBUG] :: flapjack-pagerduty-ack_finder :: pikelet start for Flapjack::Gateways::PagerDuty::AckFinder
2015-05-11T21:50:11.530255+09:30 [INFO] :: flapjack-web :: starting web - class
2015-05-11T21:50:11.533435+09:30 [INFO] :: flapjack-jsonapi :: starting jsonapi - class
2015-05-11T21:50:12.725175+09:30 [DEBUG] :: flapjack-pagerduty-ack_finder :: send_pagerduty_event got a return code of 200 - {"status"=>"success", "message"=>"Event processed", "incident_key"=>"Flapjack is running a NOOP"}
2015-05-11T21:50:12.726647+09:30 [DEBUG] :: flapjack-pagerduty-ack_finder :: looking for acks in PagerDuty for unack'd problems
2015-05-11T21:50:12.727016+09:30 [WARN] :: flapjack-pagerduty-ack_finder :: NoMethodError undefined method `msetnx' for nil:NilClass
2015-05-11T21:50:12.727137+09:30 [WARN] :: flapjack-pagerduty-ack_finder :: /Users/jesse/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/zermelo-1.1.0/lib/zermelo/locks/redis_lock.rb:81:in `block in do_lock'
/Users/jesse/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/zermelo-1.1.0/lib/zermelo/locks/redis_lock.rb:75:in `loop'
/Users/jesse/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/zermelo-1.1.0/lib/zermelo/locks/redis_lock.rb:75:in `do_lock'
/Users/jesse/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/zermelo-1.1.0/lib/zermelo/locks/redis_lock.rb:64:in `block in do_lock_with_timeout'
/Users/jesse/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/zermelo-1.1.0/lib/zermelo/locks/redis_lock.rb:203:in `call'
/Users/jesse/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/zermelo-1.1.0/lib/zermelo/locks/redis_lock.rb:203:in `block in with_timeout'
/Users/jesse/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/zermelo-1.1.0/lib/zermelo/locks/redis_lock.rb:202:in `loop'
/Users/jesse/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/zermelo-1.1.0/lib/zermelo/locks/redis_lock.rb:202:in `with_timeout'
/Users/jesse/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/zermelo-1.1.0/lib/zermelo/locks/redis_lock.rb:64:in `do_lock_with_timeout'
/Users/jesse/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/zermelo-1.1.0/lib/zermelo/locks/redis_lock.rb:24:in `lock'
/Users/jesse/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/zermelo-1.1.0/lib/zermelo/backends/base.rb:100:in `lock'
/Users/jesse/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/zermelo-1.1.0/lib/zermelo/records/class_methods.rb:53:in `lock'
/Users/jesse/src/flpjck/flapjack/lib/flapjack/gateways/pager_duty.rb:218:in `find_pagerduty_acknowledgements'
/Users/jesse/src/flpjck/flapjack/lib/flapjack/gateways/pager_duty.rb:197:in `block (2 levels) in start'
/Users/jesse/.rbenv/versions/2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/jesse/src/flpjck/flapjack/lib/flapjack/gateways/pager_duty.rb:189:in `block in start'
/Users/jesse/src/flpjck/flapjack/lib/flapjack/gateways/pager_duty.rb:188:in `loop'
/Users/jesse/src/flpjck/flapjack/lib/flapjack/gateways/pager_duty.rb:188:in `start'
/Users/jesse/src/flpjck/flapjack/lib/flapjack/pikelet.rb:146:in `block in start'
/Users/jesse/src/flpjck/flapjack/lib/flapjack/pikelet.rb:73:in `block (2 levels) in start'
/Users/jesse/src/flpjck/flapjack/lib/flapjack/pikelet.rb:70:in `loop'
/Users/jesse/src/flpjck/flapjack/lib/flapjack/pikelet.rb:70:in `block in start'
2015-05-11T21:50:12.729308+09:30 [DEBUG] :: flapjack-pagerduty-notifier :: pikelet exception stop for Flapjack::Gateways::PagerDuty::Notifier
2015-05-11T21:50:12.729429+09:30 [INFO] :: flapjack :: shutting down server
2015-05-11T21:50:12.729491+09:30 [INFO] :: flapjack :: shut down server
2015-05-11T21:50:12.729840+09:30 [INFO] :: flapjack :: shutting down server
2015-05-11T21:50:12.729883+09:30 [INFO] :: flapjack :: shut down server
 done.
```

**Comment by jessereynolds** [comment]
I also tried switching to latest zermelo on github but the error was the same. It looks like AckFinder pikelet is not being initialised with a redis connection correctly.

**Comment by jessereynolds** [comment]
@ali-graham I fixed the specs by commenting out the following lines that I replicated from `PagerDuty::Notifier`, but maybe these lines are needed and I should instead fix the specs? 

```ruby
begin
  ...
ensure
  Flapjack.redis.quit
end
```
