### ISSUE TITLE
Flapjack is pathological with redis connection attempts

### ISSUE THREAD

**Issue by jessereynolds** [flapjack/flapjack#886]
When Redis is stopped, Flapjack tries to reconnect over and over at such a high rate. This can cause problems with the network stack. 

Find out which pikelet(s) cause this and put in a sleep between connection attempts (eg 1 second).

**Comment by andsens** [comment]
It's weird that you ran into this just a day ago. I woke up to flapjack having filled the logs with messages about failed redis reconnection attempts.
```
$ du -hs /var/log/user.log /var/log/syslog /var/log/flapjack/flapjack.log 
2.9G    /var/log/user.log
2.9G    /var/log/syslog
36G     /var/log/flapjack/flapjack.log
```

**Comment by jessereynolds** [comment]
@andsens eek ... does the log show which component is making the majority of reconnection attempts?

**Comment by andsens** [comment]
It was only after I cleared the syslog and the flapjack log that I thought of doing a gzipped backup of those files for post-mortem analysis.

Here is the line that is repeated in the user.log.
```
Jul  8 15:30:54 ops flapjack[26848]: 2015-07-08T15:30:54+02:00 [ERROR] :: flapjack-email :: Error generating or dispatching email message: Redis::CannotConnectError: Error connecting to Redis on localhost:6379 (ECONNREFUSED)
#012/usr/local/rvm/gems/ruby-2.2.1/gems/redis-3.0.7/lib/redis/client.rb:290:in `rescue in establish_connection'
#012/usr/local/rvm/gems/ruby-2.2.1/gems/redis-3.0.7/lib/redis/client.rb:285:in `establish_connection'
#012/usr/local/rvm/gems/ruby-2.2.1/gems/redis-3.0.7/lib/redis/client.rb:79:in `block in connect'
#012/usr/local/rvm/gems/ruby-2.2.1/gems/redis-3.0.7/lib/redis/client.rb:257:in `with_reconnect'
#012/usr/local/rvm/gems/ruby-2.2.1/gems/redis-3.0.7/lib/redis/client.rb:78:in `connect'
#012/usr/local/rvm/gems/ruby-2.2.1/gems/redis-3.0.7/lib/redis/client.rb:240:in `with_socket_timeout'
#012/usr/local/rvm/gems/ruby-2.2.1/gems/redis-3.0.7/lib/redis/client.rb:178:in `call_with_timeout'
#012/usr/local/rvm/gems/ruby-2.2.1/gems/redis-3.0.7/lib/redis.rb:1038:in `block in _bpop'
#012/usr/local/rvm/gems/ruby-2.2.1/gems/redis-3.0.7/lib/redis.rb:37:in `block in synchronize'
#012/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
#012/usr/local/rvm/gems/ruby-2.2.1/gems/redis-3.0.7/lib/redis.rb:37:in `synchronize'
#012/usr/local/rvm/gems/ruby-2.2.1/gems/redis-3.0.7/lib/redis.rb:1035:in `_bpop'
#012/usr/local/rvm/gems/ruby-2.2.1/gems/redis-3.0.7/lib/redis.rb:1064:in `blpop'
#012/usr/local/rvm/gems/ruby-2.2.1/gems/em-synchrony-1.0.4/lib/em-synchrony/connection_pool.rb:81:in `block in method_missing'
#012/usr/local/rvm/gems/ruby-2.2.1/gems/em-synchrony-1.0.4/lib/em-synchrony/connection_pool.rb:25:in `execute'
#012/usr/local/rvm/gems/ruby-2.2.1/gems/em-synchrony-1.0.4/lib/em-synchrony/connection_pool.rb:80:in `method_missing'
#012/usr/local/rvm/gems/ruby-2.2.1/gems/flapjack-1.5.0/lib/flapjack/data/alert.rb:120:in `next'
#012/usr/local/rvm/gems/ruby-2.2.1/gems/flapjack-1.5.0/lib/flapjack/gateways/email.rb:54:in `start'
#012/usr/local/rvm/gems/ruby-2.2.1/gems/flapjack-1.5.0/lib/flapjack/pikel
```

I *think* it was something equivalent in the flapjack log. And I think the syslog wasn't filled by flapjack that was just because a lot of stuff happened on that server over the week.

**Comment by ali-graham** [comment]
Possibly related: https://github.com/redis/redis-rb/issues/415

**Comment by CVTJNII** [comment]
This just knocked a few nodes over in my environment, flapjack-email appears to be the culprit for me as well:

```
{"log":"2015-10-28T21:51:17.130846+00:00 [ERROR] :: flapjack-email :: Error generating or dispatching email message: Redis::CannotConnectError: Error connecting to Redis on flapjackredis01.mci01.mon.ops.corvisa.net:6379 (ECONNREFUSED)\n","stream":"std
out","time":"2015-10-28T21:51:30.58069612Z"}
{"log":"/var/lib/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:290:in `rescue in establish_connection'\n","stream":"stdout","time":"2015-10-28T21:51:30.580734463Z"}
{"log":"/var/lib/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:285:in `establish_connection'\n","stream":"stdout","time":"2015-10-28T21:51:30.58077054Z"}                                                                                                {"log":"/var/lib/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:79:in `block in connect'\n","stream":"stdout","time":"2015-10-28T21:51:30.580803643Z"}                                                                                                    {"log":"/var/lib/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:257:in `with_reconnect'\n","stream":"stdout","time":"2015-10-28T21:51:30.580832256Z"}                                                                                                     {"log":"/var/lib/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:78:in `connect'\n","stream":"stdout","time":"2015-10-28T21:51:30.580848903Z"}                                                                                                             {"log":"/var/lib/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:240:in `with_socket_timeout'\n","stream":"stdout","time":"2015-10-28T21:51:30.580864853Z"}                                                                                                {"log":"/var/lib/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:178:in `call_with_timeout'\n","stream":"stdout","time":"2015-10-28T21:51:30.58088143Z"}
{"log":"/var/lib/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:1038:in `block in _bpop'\n","stream":"stdout","time":"2015-10-28T21:51:30.580897533Z"}                                                                                                           {"log":"/var/lib/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:37:in `block in synchronize'\n","stream":"stdout","time":"2015-10-28T21:51:30.58091374Z"}                                                                                                        {"log":"/usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'\n","stream":"stdout","time":"2015-10-28T21:51:30.580932597Z"}
{"log":"/var/lib/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:37:in `synchronize'\n","stream":"stdout","time":"2015-10-28T21:51:30.58094927Z"}                                                                                                                 {"log":"/var/lib/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:1035:in `_bpop'\n","stream":"stdout","time":"2015-10-28T21:51:30.580965147Z"}
{"log":"/var/lib/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:1064:in `blpop'\n","stream":"stdout","time":"2015-10-28T21:51:30.580981Z"}
{"log":"/var/lib/gems/2.1.0/gems/em-synchrony-1.0.4/lib/em-synchrony/connection_pool.rb:81:in `block in method_missing'\n","stream":"stdout","time":"2015-10-28T21:51:30.580996797Z"}                                                                      {"log":"/var/lib/gems/2.1.0/gems/em-synchrony-1.0.4/lib/em-synchrony/connection_pool.rb:25:in `execute'\n","stream":"stdout","time":"2015-10-28T21:51:30.58101307Z"}                                                                                       {"log":"/var/lib/gems/2.1.0/gems/em-synchrony-1.0.4/lib/em-synchrony/connection_pool.rb:80:in `method_missing'\n","stream":"stdout","time":"2015-10-28T21:51:30.58102904Z"}
{"log":"/var/lib/gems/2.1.0/gems/flapjack-1.6.0/lib/flapjack/data/alert.rb:120:in `next'\n","stream":"stdout","time":"2015-10-28T21:51:30.58104512Z"}                                                                                                      {"log":"/var/lib/gems/2.1.0/gems/flapjack-1.6.0/lib/flapjack/gateways/email.rb:54:in `start'\n","stream":"stdout","time":"2015-10-28T21:51:30.581060764Z"}                                                                                                 {"log":"/var/lib/gems/2.1.0/gems/flapjack-1.6.0/lib/flapjack/pikelet.rb:130:in `block in start'\n","stream":"stdout","time":"2015-10-28T21:51:30.581076587Z"}
```
