### ISSUE TITLE
Email pikelet redis connection wedges when redis goes down

### ISSUE THREAD

**Issue by CVTJNII** [flapjack/flapjack#915]
Related to #886, I'm noticing that if the email pikelet fails to connect to Redis it will throw Redis::CannotConnectError indefinitely, even if Redis recovers.  The following stacktrace is logged:

```
2015-11-05T00:15:56.738044+00:00 [ERROR] :: flapjack-email :: Error generating or dispatching email message: Redis::CannotConnectError: Error connecting to Redis on tmhaproxy01.vagrant.tjnii.local:6379 (ECONNREFUSED)
/var/lib/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:290:in `rescue in establish_connection'
/var/lib/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:285:in `establish_connection'
/var/lib/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:79:in `block in connect'
/var/lib/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:257:in `with_reconnect'
/var/lib/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:78:in `connect'
/var/lib/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:240:in `with_socket_timeout'
/var/lib/gems/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:178:in `call_with_timeout'
/var/lib/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:1038:in `block in _bpop'
/var/lib/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:37:in `block in synchronize'
/usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:37:in `synchronize'
/var/lib/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:1035:in `_bpop'
/var/lib/gems/2.1.0/gems/redis-3.0.7/lib/redis.rb:1064:in `blpop'
/var/lib/gems/2.1.0/gems/em-synchrony-1.0.4/lib/em-synchrony/connection_pool.rb:81:in `block in method_missing'
/var/lib/gems/2.1.0/gems/em-synchrony-1.0.4/lib/em-synchrony/connection_pool.rb:25:in `execute'
/var/lib/gems/2.1.0/gems/em-synchrony-1.0.4/lib/em-synchrony/connection_pool.rb:80:in `method_missing'
/var/lib/gems/2.1.0/gems/flapjack-1.6.0/lib/flapjack/data/alert.rb:120:in `next'
/var/lib/gems/2.1.0/gems/flapjack-1.6.0/lib/flapjack/gateways/email.rb:54:in `start'
/var/lib/gems/2.1.0/gems/flapjack-1.6.0/lib/flapjack/pikelet.rb:130:in `block in start'
```

I've seen this exception repeating with Redis up.

I have not found a reliable means to reproduce this yet, but it aligns with the behavior seen in #886 where Flapjack will emit this error until the logs fill the disk.

**Comment by CVTJNII** [comment]
Based on the behavior I'm seeing I believe this to be an upstream bug.  There is some sort of a race involved as I haven't been able to (intentionally) reproduce this yet.

**Comment by CVTJNII** [comment]
This is larger than the email pikelet, though that's the noisiest in the logs.  I just had this happen due to a transient network issue causing Sentinel to promote a Redis slave to master, causing the connection to be interrupted as haproxy transitioned.  At the same time I began seeing these logs and the API went unavailable with flapjack-diner throwing '/usr/lib/ruby/2.1.0/net/protocol.rb:158:in `rescue in rbuf_fill': Net::ReadTimeout (Net::ReadTimeout)'.

In our environment this bug is getting nasty, I'm going to have to try to root cause and squish it.  Any advice would be appreciated as I've I haven't done any deep-dives into the Flapjack code yet.

**Comment by ali-graham** [comment]
I think Flapjack's relying on Redis for clean shutdown :( which is not ideal. The thing to do is probably not to run this line https://github.com/flapjack/flapjack/blob/maint/1.x/lib/flapjack/coordinator.rb#L61 if the error is Redis-related.

As with many other things, this is fixed in v2; master's pretty much code-complete for that, but other issues at work have stopped me getting any time to fix the documentation to be ready for release.

**Comment by CVTJNII** [comment]
Hmm, so is there a release date for v2?  I've been under the impression it was still a ways out but maybe that impression is false.  I have my prod cluster up but it's still pre-prod as nothing is sending real data to it yet, I could still switch to v2 and sidestep this bug if v2 is ready.

**Comment by ali-graham** [comment]
I'm still cautious of making promises (every time I mention even a soft target something seems to happen) but I'm aiming to at least have a pre-release (enough updated documentation to be useful, maybe some gaps) out by the end of this month. I'm working on API documentation generation at the moment, which (assuming it's not too clunky) will lessen the manual writing load a lot.

When I say that "this is fixed" in v2 this is the logged behaviour when I stop Redis while flapjack is running:

```
2015-11-11T14:30:07.274925+10:30 [WARN] :: flapjack-processor :: Redis::CannotConnectError Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)
2015-11-11T14:30:07.275009+10:30 [WARN] :: flapjack-processor :: /Users/ali/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:331:in `rescue in establish_connection'
/Users/ali/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:317:in `establish_connection'
/Users/ali/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:94:in `block in connect'
/Users/ali/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:279:in `with_reconnect'
/Users/ali/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:93:in `connect'
/Users/ali/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:350:in `ensure_connected'
/Users/ali/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:207:in `block in process'
/Users/ali/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:292:in `logging'
/Users/ali/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:206:in `process'
/Users/ali/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:112:in `call'
/Users/ali/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis.rb:765:in `block in msetnx'
/Users/ali/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis.rb:37:in `block in synchronize'
/Users/ali/.rbenv/versions/2.2.3/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/ali/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis.rb:37:in `synchronize'
/Users/ali/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/redis-3.2.1/lib/redis.rb:764:in `msetnx'
/Users/ali/Work/github/flapjack/flapjack/lib/flapjack/redis_proxy.rb:44:in `method_missing'
/Users/ali/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/zermelo-1.4.0/lib/zermelo.rb:98:in `method_missing'
/Users/ali/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/zermelo-1.4.0/lib/zermelo/locks/redis_lock.rb:81:in `block in do_lock'
/Users/ali/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/zermelo-1.4.0/lib/zermelo/locks/redis_lock.rb:75:in `loop'
/Users/ali/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/zermelo-1.4.0/lib/zermelo/locks/redis_lock.rb:75:in `do_lock'
/Users/ali/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/zermelo-1.4.0/lib/zermelo/locks/redis_lock.rb:64:in `block in do_lock_with_timeout'
/Users/ali/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/zermelo-1.4.0/lib/zermelo/locks/redis_lock.rb:203:in `call'
/Users/ali/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/zermelo-1.4.0/lib/zermelo/locks/redis_lock.rb:203:in `block in with_timeout'
/Users/ali/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/zermelo-1.4.0/lib/zermelo/locks/redis_lock.rb:202:in `loop'
/Users/ali/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/zermelo-1.4.0/lib/zermelo/locks/redis_lock.rb:202:in `with_timeout'
/Users/ali/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/zermelo-1.4.0/lib/zermelo/locks/redis_lock.rb:64:in `do_lock_with_timeout'
/Users/ali/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/zermelo-1.4.0/lib/zermelo/locks/redis_lock.rb:24:in `lock'
/Users/ali/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/zermelo-1.4.0/lib/zermelo/backend.rb:109:in `lock'
/Users/ali/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/zermelo-1.4.0/lib/zermelo/records/class_methods.rb:39:in `lock'
/Users/ali/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/zermelo-1.4.0/lib/zermelo/records/instance_methods.rb:174:in `block in destroy'
/Users/ali/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
/Users/ali/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:778:in `_run_destroy_callbacks'
/Users/ali/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:81:in `run_callbacks'
/Users/ali/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/zermelo-1.4.0/lib/zermelo/records/instance_methods.rb:169:in `destroy'
/Users/ali/Work/github/flapjack/flapjack/lib/flapjack/processor.rb:115:in `ensure in start'
/Users/ali/Work/github/flapjack/flapjack/lib/flapjack/processor.rb:116:in `start'
/Users/ali/Work/github/flapjack/flapjack/lib/flapjack/pikelet.rb:150:in `block in start'
/Users/ali/Work/github/flapjack/flapjack/lib/flapjack/pikelet.rb:77:in `block (2 levels) in start'
/Users/ali/Work/github/flapjack/flapjack/lib/flapjack/pikelet.rb:74:in `loop'
/Users/ali/Work/github/flapjack/flapjack/lib/flapjack/pikelet.rb:74:in `block in start'
2015-11-11T14:30:07.275464+10:30 [INFO] :: flapjack-coordinator :: shutting down server
2015-11-11T14:30:07.275518+10:30 [INFO] :: flapjack-coordinator :: shut down server
2015-11-11T14:30:07.275803+10:30 [INFO] :: flapjack-coordinator :: shutting down server
2015-11-11T14:30:07.275924+10:30 [INFO] :: flapjack-coordinator :: shut down server
```

The 'shutting down' lines are the web and API components, could be better denoted, as one component raising an exception forces all of them to quit. Using the Redis driver's `:reconnect_attempts` setting might handle transient failures without raising the exception into Flapjack's code..

**Comment by CVTJNII** [comment]
Okay, I think I'll stay on 1.x until 2.x is release ready, then.  If it's going to be soon I may just workaround this bug by making Flapjack die on this exception.  I'm running Flapjack in 3 node clusters with Docker restarting failed instances so that will probably be an acceptable stopgap until 2.x is ready.

**Comment by jessereynolds** [comment]
Closing as we're not going to try and fix this in Flapjack 1.x and it's already fixed in 2.x. @ali-graham re-open if I got this wrong.
