### ISSUE TITLE
flapjack crashes on wrong regex in rules

### ISSUE THREAD

**Issue by slune** [flapjack/flapjack#921]
```
2015-11-24T23:20:06.447241-08:00 [DEBUG] :: flapjack-notifier :: considering rule with entities: , entities regex: [],
                           tags: null and regex tags: "#<Set:0x000000025feb30>"
/opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-1.4.0/lib/flapjack/data/notification_rule.rb:158:in `block (2 levels) in match_regex_tags?': target of repeat operator is not specified: /*puppet*/ (RegexpError)
        from /opt/flapjack/embedded/lib/ruby/2.1.0/set.rb:263:in `each_key'
        from /opt/flapjack/embedded/lib/ruby/2.1.0/set.rb:263:in `each'
        from /opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-1.4.0/lib/flapjack/data/notification_rule.rb:157:in `block in match_regex_tags?'
        from /opt/flapjack/embedded/lib/ruby/2.1.0/set.rb:263:in `each_key'
        from /opt/flapjack/embedded/lib/ruby/2.1.0/set.rb:263:in `each'
        from /opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-1.4.0/lib/flapjack/data/notification_rule.rb:156:in `match_regex_tags?'
        from /opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-1.4.0/lib/flapjack/data/notification.rb:153:in `block (2 levels) in messages'
        from /opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-1.4.0/lib/flapjack/data/notification.rb:144:in `select'
        from /opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-1.4.0/lib/flapjack/data/notification.rb:144:in `block in messages'
        from /opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-1.4.0/lib/flapjack/data/notification.rb:129:in `collect'
        from /opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-1.4.0/lib/flapjack/data/notification.rb:129:in `messages'
        from /opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-1.4.0/lib/flapjack/notifier.rb:106:in `process_notification'
        from /opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-1.4.0/lib/flapjack/notifier.rb:69:in `start'
        from /opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-1.4.0/lib/flapjack/pikelet.rb:126:in `block in start'
```

**Comment by jessereynolds** [comment]
@slune does this occur in the latest stable version, 1.6.0 ? 1.4.0 is fairly old... 1.6.0 contains this PR that has work on the notification rule regex matchers: #871

**Comment by slune** [comment]
@jessereynolds tested on 1.6.0 and flapjack did not crashed.

**Comment by jessereynolds** [comment]
Great! Thanks for verifying that.
